《游戏设计艺术》笔记

读此书，随手记笔记，还对比《大明浮生记》的一些设定，进行了反思。

* version history
**  原始版本 2013年05月18日 12:51:36

比较完善了。

好几个透镜缺。

格式不统一。

* 前言
** 什么是游戏设计？
   游戏设计，就是做出一系列决策，来决定一个游戏该是什么样子。

** 本书试图诱导读者，从各种不同的角度来思考、审查游戏。
   这些角度被叫做透镜。

** 聚焦最基础。
   现在的游戏眼花缭乱，我们要聚焦最本质、最基础的。分析经典旧游戏。游戏设计基础，乃在于人类心理学。

** 功夫在诗外(Talk to stangers):
   万物一理，All knowledge is related。设计好游戏，就得走进生活，尝试所有事情。

** 真正的设计，在于动手实践。
   本书只能是一个开始。

** 构建你的设计地图(Map)
   要在你的脑子中，构建一个关于游戏设计的地图。本书末尾提供了一个。
   
* 透镜0: 突破想像范围的透镜
  此透镜非官方透镜，而是通过游戏设计实践悟出的。

  玩家天然喜新厌旧，总是在游戏中寻求新的体验。无论多么优秀的游戏，都会随着时间的流逝失去魅力（或边际乐趣）。

  对于某一个题材游戏、某一个主题游戏，人们会预先存在一个想像范围A，它是由常识、历史因袭、当时同类产品形成的行业惯例等决定的。

  如果游戏产品P落于这个A范围之内，则无法没有给人们边际乐趣和边际惊喜（边际是指“额外增加的”，参见《微观经济学》），就会被认为是一个平庸的产品，将被湮灭在
同类产品之中，属于同质化产品，缺乏传播（无论是媒体传播还是受众口口相传）价值。

  因此，产品要胜出，它必须突破这种想像范围。游戏的机制（玩法）、美术、故事、技术，综合体验，甚至缺陷变态设定等，只要有一个或一个以上突围，则产品被认为是
“有特色”的，就会给受众额外的乐趣、注意力和惊喜感。

** [更多论据]
中里伸也： 第一个原则，我们总要考虑给玩家提供不同的惊喜。
我在这里与其给大家看，不如给大家演示一下。（观看视频）这是《魂斗罗3》的最后一个BOSS，下面是 中BOSS，先出现的直升飞机，发了导弹，刚才从横向转为3D。在这里，直升飞机会下来变成一个机器人，会有一个大的乌龟。大家看到这儿，一定会觉得它是 最大的BOSS了吧？其实在经过了一定的打之后，这个才是最后的BOSS。

就像这样，你不能跟着玩家的想法去走，一定要超越玩家的想象。如果有一个想法成功的话，下次再用这样的想法，恐怕玩家不会再买账了。每次想出来唯一的、不同的想法，这个其实是游戏制作人员的一个最该做的事情。

批注：金庸写小说，也是同样的思路和做法，他找几个读者聊天，让他们想象小说的下一阶段是怎么样的，然后金庸一定写出和这些读者想象不一样的东西，给读者最大惊喜感。
一定要超越玩家想象才行。

** 问自己下面问题：

1. 我的游戏，市场上有同类产品吗？有同题材产品吗？如果有，那么人们对这类产品的想像范围是什么？

2. 我应该如何突破想像范围，而使产品有特色？

3. 具体来说，游戏的机制（玩法）、美术、故事、技术，综合体验，缺陷变态设定等方面，我的产品有哪个超越了想像范围？

* 透镜1：本质体验的透镜
** 透镜描述

停止思考你的游戏，开始思考玩家的体验。

*** 我想让玩家获得什么样的体验呢？
*** 这种体验中最本质的是什么呢？
*** 如何能让我的游戏捕捉到这种本质呢？
  
你需要清楚地描述出你想要的本质体验，然后寻找各种办法尽可能地把这种本质逐步灌输到你的游戏中。

**  wii sports的例子
  抓住了“挥动遥控器是游戏中最独特的”，去掉了当初想的尽可能像真实的棒球那样的想法。


我要批注  有时为了强调游戏的关键体验，可以去掉某些真实性和现实性。所谓"Keep fun, cut the rest",就是这个意思。

** 《找你妹》的例子

给女性玩家提供你“找”的这种独特体验。外加简单，无市场竞品。

** Dungeon Crawl

去掉了火炬，而且可以自动探索，就是抓住了地牢战斗的本质体验，灭掉了多余的。


**  扩展描述
很多设计师都没有用上“本质体验的透镜”，在黑暗中摸索。

游戏设计师最终目标是传达一种体验，当你对你理想中的体验及其本质元素有着清晰的了解时，  你的设计就有了某种可以追求的目标了。

假设没有这种目标，你只能是不断在黑暗中游荡而已。

我要批注  体验第一，游戏第二。

我要批注  体验胜过游戏。游戏不是体验，游戏只是为了达到体验的手段之一。

我要批注  同样的游戏机制和数值，由于包装不同，体验完全不同，一个可以被认为是好游戏，另一个可以是垃圾。

我要批注  体验是由界面，声音，美术，数值等综合产生的。

* 透镜2:惊喜感的透镜
** 透镜描述
  惊喜感是如此的基础，使得我们会轻易地忽略它。利用这个透镜提醒你，在游戏中填入各种有趣的惊喜，问一下自己以下的问题。
*** 玩家在玩我游戏时，我会用什么来让玩家感到惊喜呢？
*** 我游戏的故事有让人惊喜的元素吗？各种游戏规则呢？美术部分呢？技术部分呢？

《大明浮生记》 美术部分的惊喜感能够一瞬间抓住玩家。

 故事是个老套故事。但老套故事容易让人理解。
*** 规则能让玩家相互制造惊喜吗？
   
《大明浮生记》的相互通缉，制造了这种惊喜感，因为玩家入狱后，【基于规则】会有别的玩家捞他出来。

*** 规则能让玩家自己制造惊喜吗？

   惊喜感是所有娱乐方式中至关重要的一部分-----它是幽默、策略和问题解决的基础。我们大脑是铁定喜欢惊喜感的。
在一次试验中，参加试验的人都会张开嘴去尝糖水和白开水，那些在两种水之间随机尝的人，比那些一直固定只品尝一种的人要感觉更快乐，即使他们品尝到的糖水的总量是一样的。

   
   抽奖是制造惊喜感的手段。

** 扩展描述
《大明》这个游戏，我会用什么来让玩家感到惊喜呢？

风格上，轻松快乐,戏搞

无所不在的幽默感

独特的游戏界面让人眼前一亮，避免了同质化。

** 应用

《大明》的野怪中心，原先是若干无区别的野怪（等级稍微有差异的怪物，一律黑白颜色），玩家会觉得：
1.打多了，无惊喜感导致的厌倦 
2。无选择（或无明显区别的选择），
3.没有三角平衡（见透镜33)

改进： 

每波怪物中，随机出现零个或一个BOSS怪物，它是彩色的（参见透镜59：界面维度增加了颜色），难度大，
但是打了之后收益大。这样：

1. 有惊喜感
2. 玩家有了有意义的选择
3. 出现三角平衡（或打小怪得到平常收益，或打大怪得到大收益，但对玩家有风险）

上述设定中，利用了好几个透镜。

* 透镜3: 乐趣的透镜
** 透镜描述
   乐趣几乎在每个游戏中都是需要的。尽管有时乐趣经不起分析。为了让你的游戏的乐趣得到最大化，问一下自己这些问题。

*** 我的游戏哪个部分有趣？为什么这么说？
*** 哪些部分需要变得更有趣？

涂鸦墙
通缉令---玩家互动
联盟地下室---很搞
杀怪的技能动画（理论上）

*哪些部分需要变得更有趣？

打工系统,它枯燥无聊，没什么特色
科举考试
打副本

* 透镜4 好奇心的透镜
** 透镜描述
*** 思考玩家真正的动机---它不单单是游戏中设定的各种目标，还包括了玩家想要达到这些目标的原因。问一下问题：
*** 我的游戏，在玩家脑海中根植了哪些问题呢？
*** 我做了哪些事情让玩家在意这些问题呢？
*** 如何能让玩家产生更多的问题呢？
** 扩展描述
例如，一个迷宫类的游戏可能在每个关卡里都有限时的目标，玩家在不断地问这个问题：“我可以在30秒内找到迷宫的出口吗？”
让玩家更在意这个问题的手法，可以在他们解决每个迷宫时有趣的动画上做文章，从而让玩家可能产生另外一个问题：“我很好奇下一段动画会是怎么样的。”

我要批注：  
《大明浮生记》的浮生历程，就是在他们解决每个城市进入的时候，动画上做文章，从而让玩家可能产生另外一个问题：“我很好奇下一个城市的动画会是怎么样的。”


* 透镜5  内生价值
** 透镜描述
*** 在我的游戏中哪些东西是对玩家有价值的？

**** 等级、经验、战功、金币。
**** "混“的指标---成就系统。
游戏的特别之处是”混“，而不是武功很强。
成就的指标对玩家是有价值的。

*** 思考下，哪些东西没有表现出价值？
**** 玩家采集到的特产（对玩家有什么价值？）
在前期，成为金币来源之一。
后期，成为名将喜好品。

如果突然让某特产的系统收购价提高，将导致金币来源控制不住。设计存在问题。

**** "混“的指标---成就系统。
游戏的特别之处是”混“，而不是武功很强。
成就的指标对玩家是有价值的。
**** PK威望
PK威望小于1300才能招。
大家不认可这个设定。

招人的条件：
PK威望高，加少数特产
PK威望低，加多个特产
都能让玩家耗时间。

*** 如何能让它们对玩家显得更有价值呢？

**** 成就系统分数越高，玩家在战斗中越厉害？或者越能用较少的钱成为VIP?
**** 玩家的特产越多，就越?
**** 玩家等级。技能。装备。能让玩家。。。。。

*** 游戏中的价值与玩家的动机如何链接起来？

玩家的动机是，放松？

玩家的动机是，娱乐？

玩家的动机是，搞笑？

如何连接起来？

** 扩展描述
记住，游戏中物品的价值和各种分数能直接反映出玩家有多在意在你的游戏中获得成功。

通过思考玩家真正在意什么，以及为什么在意这些，你通常能了解如何对游戏进行改良。
** 实际例子
Bubsy游戏中的纺线球：收集能得到更高分数，但玩家不在乎，也不收集。为什么呢？因为玩家的动机仅仅是完成关卡，高分对此无任何帮助，而且高分也无任何奖励。

对比：刺猬索尼克2, 你收集戒指，收集到的戒指对玩家很重要，有很大的内生价值----因为戒指能保护你不受敌人攻击，每收集100个戒指，能额外得到一条命。

《大明》的特产，现在也没有用处，无内生价值不强。

《大明》的混世技能，现在也没有用处，无内生价值不强。

《大明》的PK威望，现在也没有用处，无内生价值不强。


* 透镜6  问题解决的透镜

思考玩家要在你游戏中成功所必须解决的问题。
** 我的游戏让玩家去解决哪些问题？

自身升级成长

获得武器和技能

强化武器和技能

打副本通关，去更牛的城市

然后才能打败怪物和别的玩家

** 游戏中有些作为玩法中的一部分的隐藏问题需要解决吗？

** 如何能让我的游戏产生各种新的问题，以此来让玩家继续回来玩？

通缉系统能让玩家之间产生新的问题，因为玩家需要打败新玩家

隐藏地点的设计不错，因为玩家的等级，可能进入不了某个他发现的隐藏地点（或精英副本），所以对他来说，是一个产生新问题的机制，让玩家继续回来玩。

很多游戏对玩家过关进行评价，例如《保卫萝卜》，有的玩家为了一个好评价，不断玩同一关。

* 透镜7 基本四元组的透镜
** 透镜描述
游戏，是由机制、故事、技术和美感四元素组成的。

观察你游戏的组成，单独考虑它们，然后再整体地考察它们。

*** 我的游戏用上了机制、故事、技术和美感四个元素了吗？

故事要编写剧情。

***  我可以通过改良一种或多种元素来提升游戏吗？

最给力的主要是美感？


*** 这四种元素是相互协调，相互加强，为同一个主题服务吗？

一些设计师一直想着游戏内部运作的细节，但完全忽略了玩家的体验。

你不但要理解各种游戏元素及其相互的关联，你还必须一直考虑它们和体验之间的关系。

所以要同时关注游戏的皮肤（用户体验）和骨骼（游戏内在机制）


* 8 全息设计的透镜
** 透镜描述
你必须同时看到游戏中的每个方面：在看到四个元素以及玩家体验的同时，还看到它们之间的相互关联。你可以把注意力从游戏的皮肤和骨骼之间
来回切换，但更好的办法是，能全息地观察你的游戏和游戏的体验。
问：
*** 游戏中的哪些元素能使整个游戏变得愉悦？
*** 游戏中的哪些元素是削减这种体验的？
*** 如何调整这些元素来改良体验？

  To use this lens, you must see everything in your game at once: the four ele-
ments and the player experience, as well as how they interrelate. It is accepta-
ble to shift your focus from skin to skeleton and back again, but it is far better 
to view your game and experience holographically. 


** 扩展描述
其实，就是从游戏的表面体验到游戏的有机组成两个不同层次、以及它们如何相互作用来来观察游戏、改进游戏的设计。

这就是全息设计的本质。

游戏的皮肤：游戏体验。

游戏的骨骼：组成游戏的各元素。

一个可怕的陷阱：一些设计师，一直想着游戏内部运作的细节，但完全忽略了玩家的体验。

只关注游戏骨骼，或者只关注游戏的皮肤，都不全面。必须同时关注两个方面。

你要把注意力在游戏皮肤和骨骼之间来回切换。

*游戏中的哪些元素能使整个体验变得愉悦？

界面，语言。

*游戏总的哪些元素是削弱这种体验的？

冷却，特产，无法让玩家理解的技能。

*如何能调整这些游戏元素来改良体验？

前n次不需要冷却

特产有用化

技能简化，表现能力增加，搭配有趣

* 9 统一的透镜
*我游戏的主题是什么？

让玩家轻松搞笑地在明朝混，最终目的是当皇帝。

** 我用了每一种可能的方法去强化这个主题了吗？

美术方面，用诙谐简单的画面来表现，有一定的效果。

玩法方面，玩家从事的事情，有混的感觉。

统一的透镜和基本的四元组透镜一起运用是很棒的。先分解，再综合它们为一个主题而服务。


* 10 共鸣的透镜

** 找能引起玩家共鸣的主题。

我们讨厌那种繁琐和累的武侠RPG，它们太同质化了，没意思。

我们工作已经很累了，让我们轻松点好吗？

我们看花花绿绿的艳俗游戏界面都厌倦了，想看漫画清新的界面

我们需要发自内心的愉悦感。

这些都是《大明》能引起共鸣的主题。

* 12 问题陈述的透镜
把你的游戏看成是对某个问题的解决方案

** 我到底在解决哪种问题呢？

武侠RPG很累的模式

游戏越做越雷同的方式

** 游戏真的是这个问题的最佳解决方案吗？为什么？

是的

** 我如何知道问题是否解决了呢？

当《大明》开始口碑传播。

* 筛选创意的八个步子

** 1. 美感上的刺激。
这个游戏感觉对头吗？
** 2.受众的统计数据
目标受众会足够喜欢这个游戏吗？
** 3. 体验设计
把你所知道的能用来创造一种出色的体验的所有东西都考虑进去，包括美感，兴趣曲线，共鸣的主题，游戏平衡，以及其他。
这是一个良好设计的游戏吗？
** 4. 创新
给玩家一些从来没有见过的东西.

这个游戏足够新颖吗？

** 5.商业和市场营销
这个游戏能卖得火吗？
** 6.技术角度
这个游戏在技术上有可能作出来吗？
** 7.社会/社区角度
这个游戏满足我们社会上的目标吗？
** 8.游戏测试
参加游戏测试的入足够喜欢这个游戏吗？


* 透镜13 八滤镜的透镜
你的设计必须满足众多的约束，只有当它无需再进行修改地通过了所有的八个滤镜时，你才能声称你的设计是最终成型的。
+这个游戏感觉对头吗？
+目标受众足够喜欢这个游戏吗？
+这是一个良好设计的游戏吗？
  我要批注  废话，什么叫“良好设计”的？如何量化和可评估呢？
+这个游戏足够新颖吗？
  我要批注  不错，挺新的。
+这个游戏会卖得火吗？
+这个游戏在技术上有可能做得出来吗？
+这个游戏满足我们社会上和社区上的目标吗？
我要批注  这是什么意思呢？
+参与测试的人，足够喜欢这个游戏吗？
我要批注  还好，有4%的人喜欢，而且成为了fans

* 游戏开发中的循环技术
** 1.提出一个基础设计
** 2.找出设计中最大的风险
** 3.建立各种原型来减轻这些风险
** 4.测试和检验这些原型
** 5.基于你已经了解的，提出一个更详细的设计
** 6.回到步骤2  

下面的透镜14,15以及原型制作技巧，都是为了实践这个循环的。

* 透镜14 风险减轻的透镜
** 透镜描述
停止去正面思考你的游戏，开始想游戏的风险：

*** 有哪些因素会阻碍这个游戏变得优秀？

我要批注：当前风险如下：  
1. 性能卡, 前主程导致，幸亏田老师正在修正，风险正在减少。

2. 数值设定不合理，这是某大神水平差造成的，现在正在修正。

3. 玩家体验很差，这个我来主抓。

4. 存在漏洞，被玩家利用，造成各种不公平或者不可接受的情形出现。

5. 收费不成系统。这个有人在主抓，向先进游戏学习。

6. 玩法单薄，没啥可玩的。

*** 如何能阻止这些因素的发生？

1. 技术发力，做好性能优化。

2. 策划发力，做好数值。

3. 狠抓体验。
   
* 原型制作技巧

** 循环回路

*** 一、陈述问题
*** 二、对一些可能的方案进行头脑风暴
*** 三、选择一种解决方案
*** 四、列出使用这种解决方案的各种风险
*** 五、建立各种原型来减轻这种风险
*** 六、测试这些原型，如果足够好了，就停止
*** 七、陈述你要解决的新问题，回到第2步。


** 高效的原型制作技巧
*** 技巧1 ： 回答一个问题
  每次制作游戏原型，要回答一个到多个问题。
应该清晰地称述这些问题。
把注意力只放在回答好关键问题上，抵制把原型做得过分精致的诱惑。
原型可能回答类似下面的问题：
  我们游戏的核心玩法有趣吗？它能长时间保持有趣吗？
  从美感上来说，我们的角色和背景设定相互符合吗？
  这个游戏需要多少关卡？
*** 技巧2: 忘掉质量
   原型制作是为了回答问题的，所以做出的速度越快越好，不要追求质量。
   你绕不开循环原则，所以越快进行循环，越好。
*** 技巧3: 别对它太依恋
   这是原型，所以它的意义在于回答问题，其余皆可抛弃。
*** 区分优先级
   消除风险的时候，可能面临多个风险。要分析这些风险，第一时间处理最大的风险。
*** 并行开发原型
   美术和技术可以并行进行原型开发。
*** 并非一定是电子版本的
   可以制作简单的桌面游戏原型
*** 选择快速游戏制作引擎
   比如python, panda3d之类的
   用它们，能够快速开发出东西，进行测试，再进行开发和调整。
*** 先创造玩具
   先制作出玩具，再制作游戏。


* 透镜15:  玩具的透镜
如果我的游戏没有任何目标，它仍然有趣吗？如果不是这样，那么怎么办？

人们看到我的游戏时，在不知道做什么之前，有和它交互之想法吗？如果没有，怎么办？

* 透镜16 玩家的透镜
游戏是为玩家做的。

爱因斯坦的小提琴的例子：启发：你必须清楚观众喜欢什么，不喜欢什么。
必须用观众能听得懂的术语和方式来表达。

** 透镜描述
用Ainstian给主要是老妇人组成的观众拉小提琴来说明：了解你的观众很重要！这些人不是为了听讲课，而是为了和著名的物理学家亲密接触。

要想打造出绝好的体验，我们必须效仿爱因斯坦。你必须清楚你的观众喜欢什么，不喜欢什么，你甚至必须比它们自己还要了解它们。做到这一点的秘籍，
在于倾听。你必须透彻且深入地倾听你的玩家，你必须紧密地和它们的思想、感情、恐惧和欲望连接在一起。

要设身处地，利用你的移情力量把自己置身于它们的位置上。

停止思考你的游戏，开始思考你的玩家
问下面的问题来了解那些玩你游戏的人：
1. 通常来说它们喜欢什么？
2. 他们不喜欢什么，为什么？
3. 他们期望在游戏总看到什么？
4. 如果我站在他们的位置，我想在游戏中看到什么？
5. 特别来说，他们喜欢和不喜欢我游戏中的哪些部分？

一个优秀的游戏设计师，应该重视去思考玩家，他应该是玩家的拥护者。

技巧熟练的设计师会同时把玩家的透镜和全息设计的透镜拿在手上，不断地对玩家、游戏体验，以及游戏中的各自机制进行同时的思考。

思考玩家的过程是很有用的，但更有用的是观察它们玩你的游戏的过程。你越多地观察它们玩游戏的过程，你就越容易地预测到她们喜欢什么。

** 扩展描述
巴图的玩家类型分类法

1. 成就型玩家  想要达成游戏中的各种目标，它们主要快乐来源是挑战

2.探索型玩家 想要了解游戏的方方面面，快乐来源于发现

3. 社交玩家 对人与人的关系很感兴趣

4 杀手型玩家 对击败别人以及与别人竞技感兴趣，感兴趣于对别人施加影响

外加一个：脑残类玩家，只是在地铁上随手打发下时间。

*** 我要批注  
对于成就类型玩家，我们游戏有成就系统，满足他们。
对于探索类型玩家，我们游戏有隐藏地点，满足他们。外加推图模式，也是探索的一种。
对于社交类型玩家，我们设计了四种类别的玩家关系，以及帮会系统，来满足他们。
对于杀手类型玩家，我们设计了PK系统和通缉系统，以及PK威望这种数值，来满足他们。

** 女人在游戏中喜欢的：
*** 情感。
*** 现实世界
*** 养育
*** 对话和迷题
*** 通过例子来学习


** 男人在游戏中喜欢的：
*** 掌握。
*** 竞技
*** 破坏
*** 空间性迷题
*** 反复试验




* 透镜#17 快乐的透镜

在使用这个透镜的时候，思考你的游戏已经提供的还没有提供的各类快乐
问问题：

你的游戏给予玩家哪些快乐？这些玩家快乐可以进一步加强吗？

哪些快乐是你的体验中遗漏的？为什么？能把它们加回来吗？

快乐：

预感

幸灾乐祸

给予礼物

幽默

可能性

成就的自豪

净化--吃光所有的豆-------消除！！

惊喜 --大脑喜欢各种惊喜

刺激

战胜逆境

好奇


人对人的信息，存了很多脸部和头部的，所以我们接受漫画中非常夸张的大头。

线条：完美地匹配了我们内部的建模机制，并且帮它们省去不少工作。为什么动漫看起来赏心悦目？因为我们的

大脑在理解事物的时候喜欢那些只需更少工作的。

作为游戏设计师，我们需要对这些心智模型更多加关心。因为有着简单规则的游戏就像漫画人物一样，

它们是我们容易接受和处理的预先消化过的模型。正因为这个原因让

它们玩起来感觉很放松，因为相比现实世界，它们只需我们大脑做更少的工作就能处理了，

其余的大部分复杂性早已从里面剥离。

flow的关键
一、清晰的目标。目标清晰，更容易聚焦到手头的任务上。
二、聚焦，专注，不被分心。
三、直接的反馈（立刻的反馈）。采取行动后，立刻有结果。
四、持续不断的挑战。挑战太难，人就有挫败感，人会转向选择别的感觉值得做的事情做。挑战太容易，让人感觉太无聊，人也会再次选择值得做的事情。

我要批注  过关通道的设计，达到了上面四点，还不错。


* 透镜#18 心流的透镜
** 透镜描述
  其实就是心理学家那个flow模型。
 
  思考一下，什么吸引你的玩家聚焦在游戏中的。
问自己这些问题：
1. 我的游戏有清晰的目标吗？如果没有，如何修正这个问题呢？
2. 玩家在游戏中的目标和我预期的目标一致吗？
3. 游戏中有哪些让玩家分心，乃至忘记了目标？ 如有，如何减少这些分心因素，或者把它们关系到游戏目标上。
4. 我考虑了玩家水平会逐步提升，而提供了稳定的、不容易、但也不太难的挑战了吗？
5. 玩家提升技巧的速度，是我希望的速度吗？如果不是这样，我如何改变之？

** 扩展描述
  对游戏设计师来说，研究心流是很值得的。
  产生一种行为，并把玩家推向心流的一部分关键因素如下：
  1. 清晰的目标。
  目标越清晰，越能持续聚焦在手头的任务上。
我要批注  现在提供了较为清晰的目标：去广州救父亲，去福州得到自己的皇族玉佩
  2. 没有被分心。
  分心会偷走聚焦，没有聚焦就没有心流。
我要批注  什么让我的游戏有分心？
  3. 直接的反馈。
  立刻给出反馈，能保持聚焦。
我要批注  现在打副本，有马上显示“过关进度 65%", 这就是直接的反馈。
  4. 持续不断的挑战
  人喜欢挑战。但它必须是能达到的，而且不能无聊。
我要批注  过关通道就是持续不断的挑战。0

** 分析：《北浮》提供了心流
*** 一、玩家有清晰的目标：赚钱，钱越多越好。
       玩家还有眼前的目标：赶快给村长还钱，这个目标是当下的，不完成就会被村长打死，结束游戏。
*** 二、没有被分心
       玩家没有别的不相关的事情分散精力。北浮整个游戏很简单，各种功能都是围绕“赚钱”这个核心点的。
*** 三、直接的反馈
       玩家的倒卖行动，能立刻看到结果，赚了还是赔了。
*** 四、持续不断的挑战
       游戏中，玩家先倒卖小物品，然后倒卖大物品（汽车），挑战是持续不断的。

* 透镜#19 需求的透镜

停止思考游戏，思考它满足了人们什么需求。

<找你妹》满足了女性“找”的需求。
<找你妹》满足了N多人要一个简单的打发时间的需求。

* 透镜#20 评判的透镜
** 透镜描述
在确定你的游戏是否对玩家进行了良好的评判时，问一下自己下面的问题：

**** 我的游戏会评判玩家哪些方面呢？
**** 它是如何传达这种评判的？
**** 玩家感觉这种评判公正吗？
**** 玩家在乎这种评判吗？
**** 这些评判让玩家有自我提升的欲望吗？

** 扩展描述
在马洛斯需求体系的第四层，自尊心是和游戏有着最密切关联的。为什么呢？所有人一个深层次而且常见的需求是被评判。
我们内心深处都想了解自己是处于何种状态的。
事实上游戏是有目的地评判的绝好系统，这点也是它们最吸引人的特色之一。
** 应用


**** 我的游戏会评判玩家哪些方面呢？
*****   玩家传统RPG那一套的评价体系。-----俗气，无特点。
*****   玩家非传统的一套：
******  混世技能，评价了玩家混世的方方面面。这个能带来一些乐趣。
******  成就系统，评价了玩家在游戏中的各种表现。这个带来追求。
******  称号系统？评价玩家比较变态的成就？
      
**** 它是如何传达这种评判的？
***** 通过排行和数值。是否还有更好的方法呢？
***** 通过称号？
**** 玩家感觉这种评判公正吗？
***** 不知道啊。
**** 玩家在乎这种评判吗？
***** 不知道啊。
**** 这些评判让玩家有自我提升的欲望吗？
***** 应该有。

* 透镜#21 功能空间的透镜
当游戏所有表面元素都被抽取之后，游戏是在什么空间中发生的。

** 透镜描述
游戏空间是分离的还是连续的？
空间有多少个维度呢？
这个空间的边界是什么？
空间中有子空间吗？它们是如何关联的？
在抽象出这个游戏的空间时，有别的更有用的视角吗？
** 扩展
** 应用
* 透镜#22 动态状态的透镜
** 透镜描述
  想想你游戏中哪些信息会改变，而且想一想，哪些人会知晓这些改变。问：
  在我游戏中有哪些对象？
  这些对象有着哪些属性？
  每种属性有着哪些可能的状态？是什么触发了这些属性状态的改变？
  哪些状态是只有游戏知情的？
  哪些状态是所有玩家知情的？
  哪些状态是只有一部分玩家或者一个玩家知情的？
  改变游戏中对状态的知情关系，能在某种程度上改良我的游戏吗？
** 扩展描述
  玩游戏的过程，是决策的过程，而决策过程是基于信息的。确定出不同的属性和其状态，以及哪些人知道这些状态，是
你游戏机制的核心。
  对信息知情者的一点点改变，有时能从根本上改变游戏。
  一个戏剧化的做法是，让所有私秘的信息突然变得公开了。
** 应用
 在明朝中，你看不到别的玩家的重要信息（例如攻击力，装备等），除非你是他的好友。
 知情者体系图：玩家ABC， 有A自己知道的信息，有AB知道的信息，有AC知道的信息等。有大家都知道的信息，有只有游戏知道的信息等等。
 

* 透镜 #23 自发性的透镜
** 透镜描述
为了确保你的游戏中有各种有趣的自发性特征，问一下自己下面的问题：
**** 我的玩家能拥有多少种动词？
**** 每种动词作用的对象有多少？
**** 玩家能够通过多少种方法达成他们的目标？
**** 玩家能够控制的主语有多少种？
**** 各种副作用是如何改变约束关系的？

** 扩展描述
这是对行为这种机制的描述。
行为是游戏机制中的“动词”。
有两种动词：
一、操作性行为，玩家能采取的基础行为。
二、因而发生的行为，需要从高层次上去观察。他们是与玩家如何利用这些操作性行为达成目标相关的。它包含了游戏中微妙的交互方式，而且通常来说策略性很重。
这些大多数本质上不是规则的一部分，而是在玩游戏的过程中自然产生的行为和策略。
大多数游戏设计师认同，这些有趣的因而发生的行为是一个好游戏的标志。
p=因而发生的行为/操作性行为, p数值越高，游戏越有趣和有深度。
努力去创造因而发生的行为，就像管理你的花园一样，因而发生的行为是有自己生命力的，同时也是脆弱和容易被破坏的。
如果你发现了一些有趣的结果导向的行为时，要认出它们并培养它们。
但如何让它们出现呢？
下面5方法能帮助你为游戏准备好土壤并散播下自发性的种子：
1. 添加更多的动词。也就是，添加更多的操作性行为。因而行为都市在操作性行为对各种对象以及对游戏空间进行相互交互时出现的。当你添加更多的操作性行为后，交互的机会也就变多了，
从而也让自发行为更多地出现。但是，添加太多的操作性动作---尤其是那些不会相互交互的行为，会让游戏臃肿杂乱。因此，添加一个好的操作行为比专家一堆一般
行为要效果好。
2. 能作用到多种对象上的动词。这也许是造就一个简洁、优雅、有趣的游戏最强有力的武器了。
3. 能够用多于一种的方法达成目标，就造成了极为丰富的动态游戏过程，让各种事情成为可能。但这种方式呢，会带来游戏平衡性问题。
4. 多个主语。
  自发性的行为看来粗等于=主语x动词x对象。
  因此，增加主语，很有可能增加自发性行为。
5. 会改变约束条件的副作用效果。
  每当你采取一个行动，它所带来的副作用都会改变你自己或你的对手的约束情况，那是很有趣的。
  例子：
  在跳棋中，你移动一个旗子，你不但改变了你可能被吃掉的格局，还改变了你对手（以及你自己）可以移动的格局。在这个意义上，
  每一步都改变了游戏空间的本质，无论这种改变是你希望或者不希望的。
  通过迫使游戏何种的多个因素在每个操作行为中发生改变，你有很大的可能性能促使各种有趣的自发性行为突出在游戏里出现。
我要批注  中国象棋、围棋、国际象棋，都是如此，动一个旗子，就会导致游戏空1. 全部都提示，则玩家太多
2. 只有少数被提示，就不会消息狂涨，但又有这类消息出现。不然，消息很单一，无法营造气氛间的改变（自己或对方的状态都变化），而玩家要评估变化后的游戏空间
进行下一步行动，这样会改变约束条件的副作用效果凸显，自发行为突出。策略性就在其中，而策略性导致乐趣。如果玩家的某个行动不导致游戏空间的改变，
这种行动意义就不大了。

我要批注  简单规则作用在简单对象集合中，导致复杂性，而复杂性是自发性的温床。需要从数学上、实践上深入研究自发性，相信它是游戏好玩的秘籍。
需要用Ruby制造一个自发性发生引擎，简单规则作用在简单对象集合，不断调整，直到产生内在复杂性，得到好玩的结果。
需要阅读更多材料、更深入的材料，全面掌握自发性、简单与复杂。
** 应用
我要批注  上面这些方法，提供了改善明朝游戏有趣性的线索。一定要有针对性的研究。
现在游戏无趣，就是操作性动作少，因而行为少，缺乏策略。
一些改进想法：

*** 玩家采集（操作性动作），能影响自己和别人，能影响游戏空间的本质。 现在，只影响自己，乐趣和互动小。
改进思路：每个城市采集的次数有限，你采集一次，就少一次，别人不能采了（改变游戏空间本质）
     你采集的时候，动物会干扰你，打跑动物才能得到物品。
     你采集的时候，别的玩家会干扰你，PK赢了才能得到物品，否则被别的玩家抢走。
     你采集的时候，会捡到钱包（里面有元宝）

*** PK中心只有战斗，动词单一为"PK"
改进思路：
    玩家之间除了PK之外，还能偷盗、忽悠。（增加操作性动词）
   玩家A的妙手空空技能如果大于玩家B的“警惕之心”，A在PK中心对B实施“偷盗”，就有机会偷出B的一些金币或身上背包中的物品。
   玩家A的妙手空空技能如果小于玩家B的“警惕之心”，A在PK中心对B实施“偷盗”，就不能偷出B的一些金币或身上背包中的物品。

   玩家A的忽悠技能如果高于B的“警惕之心”，能够对B使用“忽悠”操作，随机让B的伙伴离开。

*** 针对副本的怪物，现在只有单一动词“打”
思路 
   针对副本的怪物，提供
   “塞钱收买”、“忽悠劝说”两个动词。
   “塞钱收买”，就是塞出1000完美刀，对方接受，玩家不通过战斗即可过关。------能够用多于一种的方法达成目标。
   “忽悠劝说”，就是玩家的“忽悠”和“亲和力”等级很高，对方接受，玩家通过劝说也能过关。----------能够用多于一种的方法达成目标。

*** 劳务市场的工作，有同一时刻工作人数的限制。
思路
  某工作，有下面标识（23/50),
  其中，23是当前工作人数，50是同时工作的人数上限。
原理：玩家工作，副作用就是占了别人的位置。
  会改变约束条件的副作用效果。
 

** 按
本透镜的实质在于，想办法扩大玩家面对的游戏状态空间。多个动词，能作用到多种对象上的动词，能够用多于一种的方法达成目标， 多个主语，
都是为了使用乘法原理扩大状态空间。s=AxBxC
会改变约束条件的副作用效果，其实就是让某个动词使状态空间的状态发生较大的改变。

* 透镜　24  行为的透镜
** 透镜描述
思考哪些是玩家能做的，哪些是它们不能做的，以及为什么会这样。
问下面的问题
*** 我的游戏中有哪些操作性行为?
*** 我的游戏有哪些因而发生的行为?
*** 我希望看到哪些因而发生的行为，如何能调整游戏来上这种情况变得可能呢?
*** 我对目前因而发生的行为和操作性行为的比例满意吗？
*** 在我的游戏中有哪些行为是玩家希望能做但不能做的？我能一定程度上通过操作性行为或者因而发生的行为来让这些变得可能吗？

确定你的游戏拥有的行为会是你作为一名游戏设计师说要做的最基础的决定。对这些行为细小的改变都会对游戏产生巨大的影响，或者会
让游戏产生极大量自发性的玩法，或者让游戏性变得可预知和单调乏味，谨慎小心地选择你的各种行为，学会倾听你的游戏和你的玩家，以此了解
你的各种选择会让哪些东西变得可能。

* 透镜　25  目标的透镜
  
** 透镜描述
为了确保你游戏的目标是合适的，而且良好平衡的，问下面的问题：
*** 我的游戏中的终极目标是什么？
*** 这个目标对玩家来说清晰可见吗？
*** 假如有一系列目标，玩家能理解吗？
*** 各种不同的目标，以一种有意义的方式相互连接吗？
*** 我设定的目标，是具体、可达成、值得去做吗？
    好的目标，有下面三个特征：
****    1. 具体。
        玩家能理解和清晰地说明他们将要达成什么样的目标。
****    2. 可达成。
        玩家需要觉得自己有机会达成这目标。如果目标让他们觉得不可实现，他们很快就会放弃。
****    3. 值得去做。
        有很多方法让能达成的目标值得去做。
        假如达成目标是一种挑战，那么仅仅是达成目标的过程就是一种奖励了。
        更进一步，可以在玩家达成目标的时候，给玩家一些有价值的东西让你的目标更值得去做。----利用快乐透镜找出奖励玩家的多种
        方式（我要批注：如何具体落实），让玩家对自己达成的成就感到自豪。（老郭批准：给称号！）
        虽然玩家达成目标的时候给玩家奖励很重要，但在玩家达成目标之前让玩家觉得奖励极具奖励性更重要！如此玩家才雄心勃勃地去完成目标。(我要批注 :
        大闹天宫在战斗之前，先告诉玩家这次战斗预料玩家能够获得什么奖励，是很强的，学习之。)
*** 我设定的短期目标和长期目标是平衡的吗？
    这种长短期目标的平衡，能让玩家知道什么是当前立刻要做的，什么是最终要达成、而且更有吸引力的的目标。
*** 玩家有机会自己去制定目标吗？





* 透镜#26 规则的透镜
** 透镜描述
深入观察你的游戏，直到你能弄懂最深沉的结构。

**** 什么是我游戏的基础规则？这些规则和操作规则的区别是什么？
基础规则是对游戏状态、这些状态何时改变、以及对状态改变的数学表达。
Foundational rules are a mathematical representation of game state and how and
when it changes。

操作规则：玩家要做什么才能玩这个游戏。
Operational Rules


**** 随着游戏的进行，玩家之间能形成“法规”或“房规”吗？
法规----Law.
Laws: These only form when games are played in serious, competitive settings,
where the stakes are high enough that a need is felt to explicitly record the rules
of good sportsmanship.

房规
 house rules are usually created by players in response to a deficiency
perceived after a few rounds of play.



**** 在我的游戏中有不同模式吗？
**** 各种规则容易理解吗？规则间有让人混淆的地方吗？如果容易混淆，我应该修正规则还是进行详细解释？

** 扩展描述
** 应用
游戏就是规则的集合，你应该投入时间和精力。


* Lens #27: The Lens of Skill

To use this lens, stop looking at your game, and start looking at the skills you
are asking of your players.
Ask yourself these questions:
** ● What skills does my game require from the player?
** ● Are there categories of skill that this game is missing?
** ● Which skills are dominant?
** ● Are these skills creating the experience I want?
** ● Are some players much better at these skills than others? Does this make
   the game feel unfair?
** ● Can players improve their skills with practice?
** ● Does this game demand the right level of skill?



* 透镜#32 有意义的选择透镜
** 透镜描述
当我们在做出有意义的选择的时候，我们感觉自己当前做的事情是很重要的。问：
**** 我让玩家做什么样的选择呢？
**** 这些选择有意义吗？它们是如何有意义的？
**** 我给了玩家数量合适的选择了吗？更多的选择会让玩家感觉强大，还是更少的选择让游戏变得更清晰？
**** 在我的游戏中有什么最优策略吗？

** 扩展描述
一个好的游戏，往往给玩家很多有意义的选择。
但选择的数量要细致设计。太多，玩家迷惑。太少，玩家感觉失落。
** 应用

我要批注  原来设计的采集，玩家没有任何选择，系统随机给玩家特产或宝石，让玩家感觉自己无能为力。失去了乐趣。后来我把
特产和宝石分开，让玩家感觉有选择。玩家体验上升了。

** 按
有意义的选择，其实质在于给玩家较大的状态空间。如果选择小，则状态空间小。如果选择无意义，则状态空间小。

* 透镜#33 三角平衡的透镜
** 透镜描述
让游戏变得有趣和刺激的很好方法：
让玩家能选择：
*** 安稳地低收益地玩
*** 冒险，高收益地玩

问：
我在游戏中设计了三角平衡吗？如果没有，如何设计它呢？
这三角关系平衡么？换句话说，得到的报酬和承担的风险是旗鼓相当的吗？

如果你希望建立三角平衡，你需要四处寻找可着手的点。
一旦建立了这种三角平衡，游戏就精彩和刺激了。

** 扩展描述
《太空侵略者》建立了这种三角平衡。玩家可以打平常普通的怪，也可打从上部快速飞过的怪物，得到分数很多，但也很危险。

我要批注  其实就是提供玩家多项选择，每个选择的风险和报酬，符合等边际法则：经济学的边际收益比上边际投入要衡定。

** 应用



* 透镜#36  竞争的透镜
** 透镜描述
确定出谁在某事情上最厉害是人类一项最基本渴求。
利用这个透镜来确保你竞争类游戏让人们想在其中获胜。问：

*** 我的游戏对玩家技能给予了一种公平的衡量吗？
*** 玩家想在我的游戏中获胜吗？为什么？
*** 赢取这个游戏是人们骄傲的事情吗？为什么？
*** 新手玩家有意在我的游戏中竞争吗？
*** 老手玩家有意在我的游戏中竞争吗？
*** 老手玩家通常肯定打败新手玩家吗？




* 透镜40  奖励的透镜

** 奖励的类型：
*** 称赞
   通过声音、文字、角色等告诉你很好。实质：游戏评判和认同你了。
*** 分数
   简单的成就评判。很管用。
*** 延长游戏
   多一条命。
*** 一种门票
  新的关卡开启奖励，一道锁着门的钥匙。。。。。。
*** 壮观场面
  过场动画

*** 表现机会
  某些玩家喜欢以特别的衣服和装饰来表现自己。实质：满足玩家想要在这个世界留下自己的印记的基本需求。
*** 力量
  玩家想要变得更强大
*** 资源
  不用说了。
*** 完成游戏
 完成所有目标，能给玩家特殊的完满感。

** 给奖励的技巧
*** 给予多种奖励，组合起来（不光是静态组合----同时给两种以上奖励，而且有动态组合---某种奖励积累到一定的程度，再给另一种奖励）
*** 让奖励多变，而不是固定不变。
   实际例子：打败怪物给　10分奖励，人们觉得没意思。搞成：打败怪物，2/3的概率得0分，1/3机会得到30分，人们觉得这个奖励很好。


** 透镜描述
你的游戏时候在适当的时间给了玩家适当数量的奖励？问：
*** 我的游戏现在给出的是哪些奖励？它还能给出别的奖励吗？
*** 当玩家在游戏里得到奖励的时候，他们感到兴奋吗？还是感到厌烦呢？为什么会这样？

*** 给玩家不能理解的奖励，等同于不给玩家奖励。我的游戏玩家，都能理解他们得到的奖励吗？
*** 我游戏中的奖励给得太有规律了吗？它们能以更多变的方式给予吗？
*** 奖励之间是如何相互关联的？有方法能让它们更好地关联起来吗？
*** 我的奖励体系是如何建立起来的？是太快还是太慢还是刚刚好呢？

** 扩展描述

** 实际例子



* 透镜42  简单/复杂的透镜

** 复杂的类型：
*** 天生复杂度

Innate complexity. When the very rules of the game get very complex, I call this
innate complexity. This is the kind of complexity that often gets a bad name. It
generally arises either because the designer is trying to simulate a complex real-
world situation, or because extra rules need to be added to a game in order to
balance it. When you see a ruleset with lots of “exception cases,” this is gener-
ally a ruleset that is innately complex. Games like this can be hard to learn, but
some people really enjoy mastering the complex rulesets.


*** 自发复杂度
Emergent complexity. This is the kind of complexity that everyone praises.
Games like Go that have a very simple ruleset that gives rise to very complex sit-
uations are said to have emergent complexity. When games are praised for being
simple and complex at the same time, it is the emergent complexity that is being
praised.
   

** 透镜描述
追求：在一个简单的系统中产生出有意义的复杂度。
*** 我游戏中，有哪些元素是具有天生复杂程度的？
*** 这些天生复杂度有途径能转变成自发复杂度吗？

*** 在游戏中，有产生自发复杂度吗？如果没有，为什么不能产生呢？

*** 我游戏中哪些元素太过简单了？

** 扩展描述

** 实际例子


** 我要批注
《围棋》的确是用简单规则达到自发性复杂的经典。
但是。。。。在我们游戏设计中，如何达到这一点呢？难啊。需要设计天才。


* Lens #43: The Lens of Elegance
** 描述
 Most “classic games” are considered to be masterpieces of elegance. Use this
lens to make your game as elegant as possible. Ask yourself these questions:
 What are the elements of my game?
*** What are the purposes of each element? Count these up to give the element an “elegance rating.”
*** For elements with only one or two purposes, can some of these be combined into each other, or removed altogether?
*** For elements with several purpose is it possible for them to take on even more?

** 应用
需要逐条分析游戏的元素。尽量确保元素不再增加的条件下，增加单个元素扛的目标数量，从而增加游戏乐趣,同时又保证了游戏较为简单。



* 透镜#49 进展可见的透镜
** 透镜描述
当玩家在解决一个复杂困难的问题时，他们需要看到自己正在做出的进展。
为了确保他们得到这种反馈，问自己下面的问题。
**** 在我的游戏或迷题中，到底什么才算是做出了进展？ 
**** 在我的游戏或迷题中，是否有足够多的进展？我有办法为其加入更多的进展吗？
**** 哪些进展是可见的，哪些进展是隐蔽的？我有办法揭示出这些隐蔽的进展吗？

** 扩展描述

让人们继续坚持搞完魔方游戏的很重要一点，在于它提供了进展感。

** 应用

我要批注  “进展可见”的确很好。
对明朝的改进，一个重要方面就是确保了“进展可见”。具体表现在：
*** 玩家打副本，进展可见。

原来的版本，“副本”就是“副本”，玩家不知道为什么要打它。打它有什么好处？我有什么进展？很迷茫。
改进思路：改为“过关通道”，并且加了Tips来显示“通向成都，打通率35%”。
做法评述：“过关通道”使玩家有清晰的目标感。
       “通向成都，打通率35%”。是进展可见。

原来的版本，副本中，每打通副本一个怪物，没有提供进展的报告。
改进思路：每打败一个怪物，就出现“过关进度：25%"这种提示，给了玩家具体、强烈的进展可见。
做法评述：
      玩家有很强的目标感和明确具体的进展可见。因此，玩家体验上来了。
      
改进思路：上一关、下一关处，出现这个过关通道的总关数，当前打通关数，这个也能给玩家明确的进展信息。

英文原文：

Lens #49: The Lens of Visible Progress
Players need to see that they are making progress when solving a difficult prob-
lem. To make sure they are getting this feedback, ask yourself these questions:
● What does it mean to make progress in my game or puzzle?
● Is there enough progress in my game? Is there a way I can add more interim
   steps of progressive success?
● What progress is visible, and what progress is hidden? Can I find a way to
   reveal what is hidden?


*** 科举考试

原来版本，”科举考场“下面，没有写明白玩家的奋斗目标，让玩家困惑。
改进思路：
   改为”考学目标：进士“，目标感就清晰了。
进一步改进：
   改为”考进士(56%)“，则进展更可见。


* 透镜57 反馈的透镜
玩家从游戏中得到的反馈包括方方面面的内容：例如评判，奖励，指引，鼓励和挑战。
利用这个透镜来确保你的反馈循环能产生你想要的体验。
在游戏的每个时刻，都问问自己以下的问题：
** 透镜描述

玩家在此刻需要了解什么呢？
玩家在此刻想要了解什么呢？
你希望玩家在此刻感受到什么呢？如何给予反馈能产生这种感受？
玩家在此刻想要感受到什么呢？她们有机会去建立一种情景来得到她们想要的感受吗？
玩家此刻的目标是什么？什么样的反馈有助于她们更接近这个目标呢？

** 扩展描述

使用这个透镜会耗费你不少的精力，因为一个游戏中的反馈是需要连续不断的，并且需要在不同的情况下给出不同的反馈。
这需要在游戏中的每个时刻都耗费一定的心力去使用这个透镜，但是你花的这些时间都是很值得的，因为它有助于确保你的
游戏是清晰的、具有挑战性的和值得去玩的。

** 应用
没有反馈的体验，是充满挫败和让人不知所措的。美国和英国过街按钮的对比：前者不给反馈，让用户相当抓狂，后者给予了反馈，用户体验很好。

我要批注  应该对每个界面(Interface)、在游戏进行的每个时刻(Movement)，问这些问题并试图解决之。这样，游戏才能对玩家体贴、友好。
        对于(I,M)二维矩阵，问问题。 
我要批注  重视玩家体验，就是理解和重视玩家的苦衷。可以动用这个透镜来实际提升。



* 透镜59 渠道和维度的透镜
任何界面的重要目标是传达信息。确定出传达必要的信息的最佳方式。步骤：
1. 列出所有信息并且划分优先等级。
   不是所有的信息都重要，因此要对信息划分等级： 每时每刻都要看的信息、经常看的信息、只需偶然看看的信息。
2. 列出信息传达的渠道
   也就是显示信息的区域，比如屏幕顶部、右下角，音效、音乐，角色聊天泡泡等。
3. 把信息映射到渠道上
   把各类信息映射到不同的渠道上。重要的信息，在最重要的渠道上。方法：部分靠直觉，部分靠经验，大部分靠反复试验---绘制很多草图。
4. 信息的维度玩家从游戏中得到的反馈包括方方面面的内容：例如评判，奖励，指引，鼓励和挑战。
利用这个透镜来确保你的反馈循环能产生你想要的体验。
在游戏的每个时刻，都问问自己以下的问题：

   每一个信息渠道都有多种维度：
    显示出数字
    数字的颜色
    数字的大小
    数字的字体
   当你在一个渠道上用多种维度来强化一项信息时，能够让你想要传达的信息变得非常清晰（多汁）。
对渠道和维度的出色利用能够打造出一个简练和布局良好的界面。

** 透镜描述
选择如何去把游戏信息映射到各种渠道和维度上是设计游戏界面的核心。问：
有哪些数据需要传达给玩家呢？又有哪些数据需要从玩家那里传来呢？
哪些数据是最重要的？
我有哪些渠道能够用来传达这些数据？
哪些渠道最合适传达哪些数据？为什么？
在不同渠道上，有哪些维度是可用的？
我该如何利用这些维度呢？

** 扩展描述


** 应用



* 透镜61 兴趣曲线的透镜
兴趣曲线是你作为游戏设计师能用上的最有用和最具多用途的工具。
** 透镜描述
能迷惑住人心的事物对于每个人都是不同的。但最让人接受的迷惑方式明显是对于每个人都类似的。
为了了解玩家的兴趣在你设计的体验过程中随时间是如何变化的，问一下自己：
*** 假如我对我的体验绘制一条兴趣曲线，那它大概是什么样的形状的？

*** 它会有一处勾人的地方吗？
*** 他有着兴趣的逐步提升，且具备周期性的休息中断吗？
*** 体验里，有一个比任何事情都有趣的大结局吗？
*** 什么样的调整，能让我拥有一条更棒的兴趣曲线吗？
*** 在我的兴趣曲线中有分形结构吗？它应该具备吗？
*** 我直觉觉察到的兴趣曲线，和观察玩家所了解到的兴趣曲线一致程度如何？如果让玩家来绘制兴趣曲线，是怎么样的呢？

** 扩展描述

** 应用

古琴音乐节的演出，就明显有一个故意制造出的兴趣曲线。艺术是相通的啊。 


* 透镜  66  障碍的透镜  <----->透镜25  目标的透镜
** 透镜描述
这个透镜，是“目标透镜”的姊妹透镜！
一个有着各种障碍的目标是值得追求的。
利用这个透镜来确保你的各种障碍是玩家想要克服的障碍。
1. 主角和目标有着什么样的关系？为什么角色会在意这个目标？
2. 角色和目标之间有着哪些障碍？
3. 在这些障碍背后存在敌对的双方吗？主角和敌对双方之间的关系是什么样的？
4. 这些障碍在难度上是逐渐提升的吗？
5. 有人说，障碍越大，故事越好，你的障碍足够大吗？它们还可以足够大吗？
6. 出色的故事往往包含着主角为了克服障碍所作出的转变。你的主角是如何转变的？

** 扩展描述
好莱坞电影剧本创作的古老箴言：
一个好的故事主要组成材料是：1）一个有着特定目标的角色 2）阻碍他达成目标的各种障碍。
在角色尝试去克服障碍的过程中，各种有趣的冲突也会随着产生。
** 应用
明朝中，明确告诉玩家，需要克服各种障碍去下一个城市。

* 故事语法:英雄历程(Hero’s Journey)
Vogler’s Synopsis of the Hero’s Journey
1. The Ordinary World — Establishing scenes that show our hero is a regular per-
son leading an ordinary life.
2. The Call to Adventure — The hero is presented with a challenge that disrupts
their ordinary life.
3. Refusal of the Call — The hero makes excuses about why he can’t go on the
adventure.
4. Meeting with the Mentor — Some wise figure gives advice, training, or aid.
5. Crossing the Threshold — The hero leaves the ordinary world (often under
pressure) and enters the adventure world.
6. Tests, Allies, Enemies — The hero faces minor challenges, makes allies, con-
fronts enemies, and learns the workings of the adventure world.
7. Approaching the Cave — The hero encounters setbacks and needs to try some-
thing new.
8. The Ordeal — The hero faces a peak life or death crisis.
9. The Reward — The hero survives, overcomes their fear, and gets the reward.
10. The Road Back — The hero returns to the ordinary world, but the problems still
aren’t all solved.
11. Resurrection — The hero faces a still greater crisis, and has to use everything
he has learned.
12. Returning with the Elixir — The journey is now well and truly complete,
and the hero’s success has improved the lives of everyone in the ordinary
world.

* Lens #68: The Lens of the Hero’s Journey
Many heroic stories have similar structure. Use this lens to make sure you
haven’t missed out on any elements that might improve your story. Ask your-
self these questions:
● Does my story have elements that qualify it as a heroic story?
● If so, how does it match up with the structure of the Hero’s Journey?
● Would my story be improved by including more archetypical elements?
● Does my story match this form so closely that it feels hackneyed?
  过于接近这种形式以至于让人觉得陈腐吗？

* 透镜#82 内在矛盾的透镜
Free from inner contradictions-----毫无内在矛盾
毫无内在矛盾对于任何设计师来说都是极为重要的，因为内在矛盾是糟糕设计的本质。
一个好的游戏不能包含了抵触游戏最关键的目的的特征。为了移出这些矛盾的特征，问一下自己下面的问题：
** 透镜描述
*** 我的游戏的目的是什么？
   给玩家轻松、幽默、懒惰的娱乐。
*** 我游戏中的每个子系统的目的是什么？
   需要列表。
*** 在我游戏中，有什么东西是从根本上抵触这些目的的呢？
  
*** 倘若这样，如何才能改变这种情况呢？

** 扩展描述
   “内在矛盾”是任何糟糕的设计的本质。
   假设一个设施能让我生活变得更轻松，但它却很难用;------矛盾
   假设某样东西应该很有趣的，但用起来却无聊而且烦人-----矛盾
   一个好的设计师必须小心地去除所有内在的矛盾，不要给它们找借口。 
** 应用
  明朝中，内在的矛盾表现在，本来我们游戏是轻松休闲玩法特别的，那么下面就会成为内在矛盾：
   1. 难用的界面 ------界面难用，不合适我们轻松的玩法
   2. 常见的、普通的厚重的玩法------如果出现类似大闹天宫的玩法，就厚重了，对我们游戏是矛盾。
   3. 让玩家难以理解的玩法--------“难以理解”，这个太糟糕了，现在的技能以及技能升级效果，都是玩家无法理解的。
   4. 平庸的玩法，无亮点和惊喜感-----平庸本来就是和我们目标矛盾的。
** 设计招式
  Christopher Alexander解释到：只有通过对该样事物的使用过程进行不断的迭代和观察，如此才能达到真正出色的设计。也就是：
循环的法则对于建筑学和游戏设计是一样通用的。
他用具体例子说明：当在一个复杂的建筑群的建筑间铺设道路的时候，可先没有路，只是种上草。然后一年后，看看人们在草地上走出什么样的
道路，再以此铺设道路。

* 实战
学习《游戏设计的艺术后》，进行了下面的实战：
** 浮生历程的设计。
玩家每打过一个城市，就有这个城市的Flash剧情，未打过的不开剧情。城市之间单线条连接起来。
应用了：

***  进展可见透镜：玩家的游戏进展是可见的。
***  好奇心透镜：玩家会好奇，下一个城市flash是什么？

** 采集场的设计
原来的设计，玩家一按按钮，就随机得到特产或者宝石。
我的设计，界面上有特产和宝石按钮，玩家自行选择按哪个，分别得到结果。
应用了：
*** 有意义的选择的透镜。  

** 太学设计
  为玩家下阵的伙伴提供经验。我的设计概要：若干城市有“太学”，提供免费的50个位置，玩家可以把自己的伙伴送到太学学习，一个伙伴
占一个位置。如果没有位置了，就得等。应用了：
***  本质体验的透镜： 这种体验是玩家可接受的
***  玩家的透镜：我们游戏的玩家不愿意理解费解的东西
***  自发性的透镜之 “5. 会改变约束条件的副作用效果。
  每当你采取一个行动，它所带来的副作用都会改变你自己或你的对手的约束情况，那是很有趣的。 例子：
  在跳棋中，你移动一个旗子，你不但改变了你可能被吃掉的格局，还改变了你对手（以及你自己）可以移动的格局。在这个意义上，  每一步都改变了游戏空间的本质，
无论这种改变是你希望或者不希望的。”。 -----我的设计中，玩家伙伴的学习占了位置，改变了你的对手（别的玩家）的格局。
   

* 基于混搭的头脑风暴技术
Brainstorm Tip #13: Mix and Match Categories
It’s great when game ideas, Athena-like, spring forth from your head, fully formed.
But it doesn’t happen that way every time. A great technique for helping ideas come
together is to brainstorm in categories. The elemental tetrad comes in handy here.
For example, you might have decided you want to make a game for teenage girls.
You might make separate lists, which you can start to mix and match. Something
like
Technology Ideas
1. Cell phone platform
2. Handheld game
3. PC
4. Integrated with instant messaging
5. Game console
Mechanics Ideas
1. Sims-like game
2. Interactive fiction game
3. The winner makes the most friends
4. Try to spread rumors about the other players
5. Try to help as many people as possible
6. Tetris-like game
Story Ideas
1. High school drama
2. College-themed
3. You play cupid
4. You’re a TV star
5. Hospital theme
72
FIFTEEN NITTY-GRITTY BRAINSTORMING TIPS
6. Music theme
a. You’re a rock star
b. You’re a dancer
Aesthetic Ideas
1. Cel shaded
2. Anime style
3. All characters are animals
4. R&B music defines the game
5. Edgy rock/punk music defines the feel
Once you have lists like these (though you should have dozens more entries on
each list!) you are free to start mixing and matching ideas — maybe a cell-phone-
based Tetris-like game, which has a hospital theme, where all the characters are
animals.... Or how about a Sims-like console game based on high school with
an anime style? By having all these lists of partial ideas that can easily be mixed
and matched, fully formed game ideas that you might never have thought of start
springing up all over the place, each taking on a life of their own. Don’t be afraid to
make up other categories, either, as you need them!

我要批注   混搭有时能突破人的思维局限，创造出意想不到的好创意。
         计算机可以用来做这个，其实质就是机械地实现乘法原理。A=BxCxDxE, B,C,D,E就是各个组成部件，A的空间很大。可以使用脚本语言来找出A,
然后通过人来在A中选择有意义的组合（子集合）作为创意集。
