《Kindom Rush》品


* version history

**  V1.00  2014年04月23日 12:31:24
1. 初版
**  V1.01  2014年05月14日 19:33:31
填写细节

* 前言
对Kingdom Rush进行品，以《游戏设计的艺术》为标准。

* 透镜0: 突破想像范围的透镜

1. 市场上有同类产品吗？有同题材产品吗？如果有，那么人们对这类产品的想像范围是什么？
答：塔防太多了。出头不容易。想象范围：萌（保卫萝卜）、高度自由（FiledRunner）、玩具题材、武侠题材....

2. 应该如何突破想像范围，而使产品有自己鲜明的特色？这是破解同质化的关键之所在。
答：做出神魔题材的塔防。里面怪物种类繁多，并且有激动人心的故事。

3. 具体来说，游戏的机制（玩法）、美术、故事、技术，综合体验，缺陷变态设定等方面，我的产品有哪个超越了想像范围？
答：机制是经典塔防。
   美术：非常精细精致。
   故事：中世纪神话，王国被怪物入侵。
   技术：不卡，流畅，无Bug，非常多同屏怪物时能正常逻辑。

* 透镜1：本质体验的透镜

1. 这游戏给玩家的本质体验是啥？能否用一句话说出来？
答：流畅多变深度足够的2D神话塔防。


2. 游戏的哪些设定引起或激活了本质体验？
答：怪物设定，地图，故事。

3. 为了让本质体验更明确、更突出，还可做什么改进？
答：可以引入玩家特殊技能，比如魔兽的某个技能。

4. 游戏的设定，是否出现了对本质体验的偏差？比如试图搞两种以上的体验，不分主次？
   例子：jelly defense出现了塔防和手动捡金币两种操作，把塔防策略本质体验搞偏移分散了。
答：没有。KR的各种设定很统一，无偏差。
   操作上，就是布置塔，升级，掉入支援炮火和队伍。唯一操作：点击。

* 透镜1.5  动态体验的透镜

这游戏的认知曲线、难度曲线和兴趣曲线是怎样的？画出来看看。

答：
认知上，一开始有一定的坡度，因为怪物和玩法需要引导。一些怪物很让人混淆。
难度曲线上，完美。表现在：
1. 一开始的难度很低。但休闲级别打3星后开启两个挑战模式，分别是HEROIC CHALLEGE，IRON CHALLENGE。难度变大，而且还
追求星星(1,2,3)，难度更大,坑更深。
2.主线自己，也是一开始简单，后来逐步增加难度，最后的关卡难度较大，但是不是过不了。
3.主线12个关卡玩通之后，作为奖励，地图上突显6个额外关卡等待玩家挑战，其难度明显高于主线，很有可能过不了，这时内生价值（金币）就
起作用了：购买道具，购买建筑。
综上所述，难度很好地做到了从最简单到最难到变态难，难度曲线是完美的、高y值的（y意味着难度）。它的排列组合手段来制造难度曲线的手段完全可以借鉴。



这游戏的前3分钟、前5分钟和前7分钟，分别表达了什么？体验是怎样的？
答：需要体验。


玩这游戏7分钟之后，玩家是否有什么不明白？什么让玩家困惑了？
答：主要是怪物的物防魔防属性。

玩这游戏7分钟之后，玩家是否想留下来继续玩？为什么？
答：希望留下来，因为前面还有具体的、稍微难一点的目标。


这游戏的节奏对劲吗？太快了以至于不明白游戏，还是太慢了以至于无聊？还是节奏紊乱或体会不到
明显的节奏感？

答：节奏不错。不快不慢。


* 透镜2:惊喜感的透镜

啥东西让玩家惊喜了？尖叫了？
答：
1. 精细制作的怪物及其自然神似的动作，属于精品。
2. 各种细节非常到位。
3. 在蘑菇那一关，居然能用100金，聘请某房屋的兵，他出面帮你！这也太帅了，让人欢喜尖叫！

游戏的故事方面有吗？
答： 故事比较烂俗。

游戏规则呢？
答：
规则很棒，做到了塔防玩法精髓。
个别BOSS出现的样子和走路路径突破了玩家想象，让人吃惊。

美术部分呢？
答：
美术很好，画得很精致。怪物走路的动作很细致流畅，各有特点。

技术部分呢？
答：
技术合格，无Bug，运行流畅，即使场面上有大量怪物和兵的时候，逻辑正确，不卡。

操作部分呢？
答：
操作上顺利流畅，但是升级建筑的操作稍嫌不方便，天上掉火那个有时候误操作。
遇到骂人的敌人BOSS那一关，敌人一边骂人，一边冰冻我方建筑，需要玩家不断点击建筑防冻。这个
操作不爽，偏离了策略游戏本意，变成了动作游戏。

如果玩家不尖叫，这游戏还有什么价值？它太同质化了以至于是天朝设计的吧。
答：这个塔防绝非天朝人可以设计出来：细致，精深，各方面都专业，游戏本身容易上手，精通很难。


* 透镜3: 乐趣的透镜

这个游戏中，啥东西很有趣？
答：不断应用各种策略打败怪物，过关。

为什么有趣？
答：
1. 因为有策略，怪兽种类多，策略也多，包括兵的微操（移动位置）
2. 因为难度梯度很大，有无尽的探索路子。

* 透镜4 好奇心的透镜

游戏中什么让玩家感到好奇，以至于有动力继续玩下去？
答：想知道下一关是怎么设计的。
   想知道还会出现什么怪。
   想知道故事会怎么发展。

玩家玩下去的动机是啥？
答：打通地图上全部关卡。

游戏中给玩家哪些目标？
答：分下面各类：
1. 地图上关卡打通，最终彻底解决困扰国家的邪恶怪物们。
2. 打通关卡之后，想在每个关卡赢得三星。
3. 打通普通关卡之后，想挑战变态难挑战模式。
4. 想获得成就，一共有70个成就。


玩家想要达到这些目标的原因是什么？
答：
1. 完成故事给的使命和目标
2. 地图强迫症，清除地图上所有未解决的关卡。

* 透镜5  内生价值

这游戏产出什么？
答：产出下面三类东西：
1. 游戏中怪物的死亡将产生金币，数量由怪物的厉害程度定。
2. 产出宝石（难度大的怪物死亡、以及游戏结束的某种参数评价）。
3. 作为玩家技能评价的星星。

产出的东西有价值吗？有几个价值？
答：有价值。
1.金币可以购买建筑和建筑的升级。
2.宝石可以购买一包金币（500)或者各种道具:额外生命、冰冻，大冰冻，原子弹，炸药包。
3.星星可以升级建筑的技能或者属性，以及外援属性。

* 透镜6  问题解决的透镜

玩家需要在游戏中解决什么问题？
答：在资源有限的情况下，如何分配资源建设建筑，挡住敌人的进攻。


* 透镜7 基本四元组的透镜

游戏机制、故事、技术和美感四元素各如何？
答：
1. 游戏有坚实的机制（塔防），它成熟，有深度。这是KR好玩的基础。
2. 游戏有一个贯穿始终的故事。
3. 技术上，确保了无Bug，不闪退，流畅。
4. 美感上，美术风格统一（西方魔幻），怪物走动真实好玩。

观察游戏的四个组成，单独考虑它们，然后再整体地考察它们。
答：整体而言，这个游戏是精品。

游戏中的哪个（些）元素能使整个游戏变得愉悦？
答：可以进一步提升美术表现力。

游戏中的哪些元素是削减这种体验的？
答：当前无。

如何调整这些元素来改良体验？
答：未知，因为已经很完美了。

* 9 统一的透镜

这游戏的主题是什么？
答：保护王国不受邪恶势力入侵，并出兵捣其老巢，彻底解决问题。
主题是一致的还是有分心的、失焦的？
答：很聚焦，没有失去焦点，也没有让玩家分心。

用了每一种可能的方法去强化这个主题了吗？
答：用了。
主题的实施手段上，是否有相互矛盾的？
答：没看见。
游戏的操作也吻合主题吗？操作是否导致游戏不好玩？
答：操作非常唯一：点击放建筑，点击升建筑，点击放大招。

* 10 共鸣的透镜

游戏中啥东西让玩家共鸣了？
答：无关。
它反应了玩家群体的什么共同感受？以什么样的方式？
答：无关。

* 12 问题陈述的透镜

把游戏看成是对某个问题的解决方案。
答：如何制作一个精良的塔防游戏，让玩家上瘾？

这游戏到底在解决哪种问题呢？

如何知道问题是否解决了呢？
答：KR出名之后，问题解决。

* 透镜13 八滤镜的透镜

你的设计必须满足众多的约束，只有当它无需再进行修改地通过了所有的八个
滤镜时，你才能声称你的设计是最终成型的。

** 这个游戏感觉对头吗？
答：感觉甚佳。
** 目标受众足够喜欢这个游戏吗？
答：目标受众到底是哪些人，目前不清楚。
    一部分玩家特别喜欢这个游戏，原因不清楚。

** 这是一个良好设计的游戏吗？
答：绝对是，四元素都OK。
  
** 这个游戏足够新颖吗？
答：不够。 
** 这个游戏会卖得火吗？
答：肯定。
** 这个游戏在技术上有可能做得出来吗？
答：已经做出来了。
** 这个游戏满足我们社会上和社区上的目标吗？
答：无法回答。
** 参与测试的人，足够喜欢这个游戏吗？
答：无法回答。

* 透镜14 风险减轻的透镜

停止去正面思游戏，开始想游戏的风险：

有哪些因素会阻碍这个游戏变得优秀？
答：1. 美术上不够美，动画不细致。
2. 数值设计不好，导致各种漏洞和不好玩，缺乏策略空间等。
3. 技术实施不行，Bug迭出，游戏不流畅。
4. 题材不招人待见（比如Toy defense）
5. 画面或者关卡细节没处理好。
6. 地图关卡太少，不耐玩。话说，KR关卡少，但开启机制，挑战关卡
开启机制，三星机制，已经让游戏太耐玩了。学习之。

如何能阻止这些因素的发生？
答：丰富的经验、周密完备的设计、严谨的态度、科学并且可行的管理。

* 透镜15  玩具的透镜

如果游戏没有任何目标，它仍然有趣吗？如果不是这样，那么怎么办？
答：好玩，就是某一个关卡也能反复玩。

人们看到我的游戏时，在不知道做什么之前，有和它交互之想法吗？
如果没有，怎么办？
答：无法回答。

* 透镜16 玩家的透镜

问下面的问题来了解那些玩游戏的人：
1. 通常来说它们喜欢什么？
2. 他们不喜欢什么，为什么？
3. 他们期望在游戏中看到什么？
4. 如果我站在他们的位置，我想在游戏中看到什么？
5. 特别来说，他们喜欢和不喜欢游戏中的哪些部分？

答：目前无法知道。

* 透镜16.5  设备相关占优操作的透镜

游戏在什么设备下是很关键的，因为玩家在该设备下有微妙的操作习惯，能影响游戏设定，顺之者昌，逆之者亡。但这经常被人忽视。
在手机上，玩家的动作就是点，划，拉。
一个手机游戏，如果用这种方式来表达核心操作，必然是被玩家广泛接受的。
一个手机游戏，如果照抄页游，很难成功，因为操作就是不一样：PC设备用鼠标操作，鼠标能精准定位且鼠标能弹起来。而人的手指是不行的。
PC上好游戏，都是鼠标加键盘的操作方式。

问：
这游戏的操作，是这个设备下玩家的习惯占优操作吗？
游戏的操作也吻合游戏主题吗？操作是否导致游戏不好玩？
这游戏的操作，如果不是这个设备下玩家的习惯占优操作，应该怎么办呢？



* 透镜#17 快乐的透镜

你的游戏给予玩家哪些快乐？这些玩家快乐可以进一步加强吗？

哪些快乐是你的体验中遗漏的？为什么？能把它们加回来吗？

快乐list：

预感

幸灾乐祸

给予礼物

幽默

可能性

成就的自豪

净化--吃光所有的豆-------消除！！

惊喜 --大脑喜欢各种惊喜

刺激

战胜逆境

好奇

* 透镜#18 心流的透镜
游戏中是否出现了flow？也就是有下面的特征：
一、清晰的目标。目标清晰，更容易聚焦到手头的任务上。
二、聚焦，专注，不被分心。
三、直接的反馈（立刻的反馈）。采取行动后，立刻有结果。
四、持续不断的挑战。

挑战太难，人就有挫败感，人会转向选择别的感觉值得做的事情做。
挑战太容易，让人感觉太无聊，人也会再次选择值得做的事情。

思考一下，什么吸引玩家聚焦在游戏中的。

问自己这些问题：

1. 游戏有清晰的目标吗？如果没有，如何修正这个问题呢？

2. 玩家在游戏中的目标和预期的目标一致吗？

3. 游戏中有哪些让玩家分心，乃至忘记了目标？ 
   如有，如何减少这些分心因素，或者把它们关系到游戏目标上？
4. 考虑了玩家水平会逐步提升，而提供了稳定的、不容易、但也不太难的挑战了吗？
5. 玩家提升技巧的速度，是希望的速度吗？如果不是这样，如何改变之？

* 透镜#19 需求的透镜

停止思考游戏，思考它满足了人们什么需求。
答：
1. kill time
2. 保护什么东西的需求
3. 取得进展的需求（推图）

* 透镜#20 评判的透镜

游戏是否对玩家进行了良好的评判？
答：评判得非常好。

游戏会评判玩家哪些方面呢？
答：
1. 应用基本策略完成塔防的游戏。
2. 应有高级策略，完成变态难度游戏。
3. 取到各种成就。
4. 过关表现（通过星星个数）

它是如何传达这种评判的？
答：
1. 是否通过游戏关卡。
2. 是否优异到开启变态关卡。
3. 每个关卡的每个模式，得到多少星星。
4. 获得的成就。

玩家感觉这种评判公正吗？
答：感觉相当公平。
玩家在乎这种评判吗？
答：非常在乎，因为星星可以升级技能，也可开启变态难度模式。

这些评判让玩家有自我提升的欲望吗？
答：有，很强烈。提升各种技能。

* 透镜#21 功能空间的透镜

当游戏所有表面元素都被抽取之后，游戏是在什么空间中发生的？

游戏空间是分离的还是连续的？

空间有多少个维度呢？

这个空间的边界是什么？

空间中有子空间吗？它们是如何关联的？

在抽象出这个游戏的空间时，有别的更有用的视角吗？

* 透镜#22 动态状态的透镜

  游戏中哪些信息会改变，而且想一想，哪些人会知晓这些改变。问：
  在游戏中有哪些对象？
  这些对象有着哪些属性？
  每种属性有着哪些可能的状态？是什么触发了这些属性状态的改变？
  哪些状态是只有游戏知情的？
  哪些状态是所有玩家知情的？
  哪些状态是只有一部分玩家或者一个玩家知情的？
  改变游戏中对状态的知情关系，能在某种程度上改良游戏吗？

* 透镜 #23 自发性的透镜

游戏呈现了自发性，就有趣了！

玩家能拥有多少种动词？
每种动词作用的对象有多少？
玩家能够通过多少种方法达成他们的目标？
玩家能够控制的主语有多少种？
各种副作用是如何改变约束关系的？

* 透镜　24  行为的透镜

问下面的问题：
游戏中有哪些操作性行为?
有哪些因而发生的行为?
希望看到哪些因而发生的行为，如何能调整游戏来上这种情况变得可能呢?
对目前因而发生的行为和操作性行为的比例满意吗？
在游戏中有哪些行为是玩家希望能做但不能做的？
能一定程度上通过操作性行为或者因而发生的行为来让这些变得可能吗？

* 透镜　25  目标的透镜
  
为了确保游戏的目标是合适的，而且良好平衡的，问下面的问题：
我的游戏中的终极目标是什么？这个目标对玩家来说清晰可见吗？
假如有一系列目标，玩家能理解吗？
各种不同的目标，以一种有意义的方式相互连接吗？
我设定的目标，是具体、可达成、值得去做吗？
* 透镜#26 规则的透镜

深入观察游戏，直到你能弄懂最深沉的结构。

什么是我游戏的基础规则？这些规则和操作规则的区别是什么？

* Lens #27: The Lens of Skill

Ask yourself these questions:
** ● What skills does my game require from the player?

** ● Are there categories of skill that this game is missing?

** ● Which skills are dominant?

** ● Are these skills creating the experience I want?

** ● Are some players much better at these skills than others? Does this make
   the game feel unfair?

** ● Can players improve their skills with practice?

** ● Does this game demand the right level of skill?

* 透镜#32 有意义的选择透镜

游戏让玩家做什么样的选择呢？
答：选择关卡----难度，怪的类型，地形。
选择塔---功能
选择塔升级方向--效用


这些选择有意义吗？它们是如何有意义的？
答：上面选择都非常有意义，对于游戏数值和玩的体验有很大影响。

给了玩家数量合适的选择了吗？更多的选择会让玩家感觉强大，还是更少的选择让游戏变得更清晰？
在游戏中有什么最优策略吗？
答：选择数量合适。不多，也不少，感觉非常合适。

* 透镜#33 三角平衡的透镜

让游戏变得有趣和刺激的很好方法：

在游戏中设计了三角平衡吗？如果没有，如何设计它呢？
这三角关系平衡么？换句话说，得到的报酬和承担的风险是旗鼓相当的吗？
答：有大致的三角平衡。表现：
前面关卡，敌人波数有限，难度有限，打赢了得到的宝石数量有限（73～～），后面的关卡怪物波数多，
时间长，难度大，但打赢了得到的宝石数量多（最多可得400以上）。
同一关卡，是不是变态难度的奖励也多？这个目前不清楚，需要探索下。

* 透镜#36  竞争的透镜
确定出谁在某事情上最厉害是人类一项最基本渴求。
游戏对玩家技能给予了一种公平的衡量吗？
答：给了。
玩家想在游戏中获胜吗？为什么？
答：肯定想，因为一是推图，二是要打三星开启变态挑战，三是完成（获得满星星）

赢取这个游戏是人们骄傲的事情吗？为什么？
答：对于塔防游戏来说，是的。
新手玩家有意在我的游戏中竞争吗？
答：不相干，因为这是单机。
老手玩家有意在我的游戏中竞争吗？
答：不相干，因为这是单机。
老手玩家通常肯定打败新手玩家吗？
答：不相干，因为这是单机。



* 透镜40  奖励的透镜

** 奖励的类型：
*** 称赞
   通过声音、文字、角色等告诉你很好。实质：游戏评判和认同你了。
*** 分数
   简单的成就评判。很管用。
*** 延长游戏
   多一条命。
*** 一种门票
  新的关卡开启奖励，一道锁着门的钥匙。。。。。。
*** 壮观场面
  过场动画

*** 表现机会
  某些玩家喜欢以特别的衣服和装饰来表现自己。实质：满足玩家想要在这个世界留下自己的印记的基本需求。
*** 力量
  玩家想要变得更强大
*** 资源
  不用说了。
*** 完成游戏
 完成所有目标，能给玩家特殊的完满感。

** 给奖励的技巧
*** 给予多种奖励，组合起来（不光是静态组合----同时给两种以上奖励，而且有动态组合---某种奖励积累到一定的程度，再给另一种奖励）
*** 让奖励多变，而不是固定不变。
   实际例子：打败怪物给　10分奖励，人们觉得没意思。搞成：打败怪物，2/3的概率得0分，1/3机会得到30分，人们觉得这个奖励很好。


** 透镜描述
你的游戏时候在适当的时间给了玩家适当数量的奖励？问：
*** 我的游戏现在给出的是哪些奖励？它还能给出别的奖励吗？
*** 当玩家在游戏里得到奖励的时候，他们感到兴奋吗？还是感到厌烦呢？为什么会这样？

*** 给玩家不能理解的奖励，等同于不给玩家奖励。我的游戏玩家，都能理解他们得到的奖励吗？
*** 我游戏中的奖励给得太有规律了吗？它们能以更多变的方式给予吗？
*** 奖励之间是如何相互关联的？有方法能让它们更好地关联起来吗？
*** 我的奖励体系是如何建立起来的？是太快还是太慢还是刚刚好呢？

** 扩展描述

** 实际例子
*** 快速找东西？给你奖励
学霸给找东西加“真快”和“神速xN”。
如果每两次找东西之间的时间间隔很少，或者持续很少，则给玩家一个很帅
的评价“真快”和“神速xN”，伴有多汁酷爽的特效哦！
这个设计很好：
1. 正确地评价了玩家（参见评价的透镜）
2. 正确地奖励了玩家，给予了“称赞”，通过声音、文字、角色等告诉你很好。

*** 新主题之开启

新主题开启，把大量新的物件以很炫的展现方式“奖赏”给玩家
是一种很好的方式。

* 透镜42  简单/复杂的透镜

** 复杂的类型：
*** 天生复杂度

Innate complexity. When the very rules of the game get very complex, I call this
innate complexity. This is the kind of complexity that often gets a bad name. It
generally arises either because the designer is trying to simulate a complex real-
world situation, or because extra rules need to be added to a game in order to
balance it. When you see a ruleset with lots of “exception cases,” this is gener-
ally a ruleset that is innately complex. Games like this can be hard to learn, but
some people really enjoy mastering the complex rulesets.


*** 自发复杂度
Emergent complexity. This is the kind of complexity that everyone praises.
Games like Go that have a very simple ruleset that gives rise to very complex sit-
uations are said to have emergent complexity. When games are praised for being
simple and complex at the same time, it is the emergent complexity that is being
praised.
   

** 透镜描述
追求：在一个简单的系统中产生出有意义的复杂度。
*** 我游戏中，有哪些元素是具有天生复杂程度的？
*** 这些天生复杂度有途径能转变成自发复杂度吗？

*** 在游戏中，有产生自发复杂度吗？如果没有，为什么不能产生呢？

*** 我游戏中哪些元素太过简单了？

** 扩展描述

** 实际例子
项目Z的物品，每个都简单，容易认，但放到一起，就复杂难找了。
好像就是，“简单”的堆彻，最终照成复杂？

** 我要批注
其实就是量变产生质变？
*** 围棋
《围棋》的确是用简单规则达到自发性复杂的经典。
但是。。。。在我们游戏设计中，如何达到这一点呢？难啊。需要设计天才。
*** 找你妹
每个物件都很简单，但放到一起，要找就比较麻烦了，复杂了。


* Lens #43: The Lens of Elegance
** 描述
 Most “classic games” are considered to be masterpieces of elegance. Use this
lens to make your game as elegant as possible. Ask yourself these questions:
 What are the elements of my game?
*** What are the purposes of each element? Count these up to give the element an “elegance rating.”
*** For elements with only one or two purposes, can some of these be combined into each other, or removed altogether?
*** For elements with several purpose is it possible for them to take on even more?

** 应用
需要逐条分析游戏的元素。
尽量确保元素不再增加的条件下，增加单个元素扛的目标数量，
从而增加游戏乐趣,同时又保证了游戏较为简单。

找你妹3的钥匙，是单一目的元素：只能开启隐藏关卡。所以设计上是不成功的。
如何改进？如果玩家拥有足够的钥匙，就能开启一个新关卡？


* 透镜#44 特色的透镜
1.在游戏里，有什么东西是很奇怪并且人们谈起来很兴奋？
2.游戏中，有着让它独一无二有趣特质的东西吗？
3.游戏中，有玩家喜欢的瑕疵吗？


* 透镜#49 进展可见的透镜

当玩家在解决一个复杂困难的问题时，他们需要看到自己正在做出的进展。问自己下面的问题。
在游戏中，到底什么才算是做出了进展？ 
在游戏中，是否有足够多的进展？我有办法为其加入更多的进展吗？
哪些进展是可见的，哪些进展是隐蔽的？
我有办法揭示出这些隐蔽的进展吗？

* 透镜57 反馈的透镜
利用这个透镜来确保你的反馈循环能产生你想要的体验。
在游戏的每个时刻，都问问自己以下的问题：

玩家在此刻需要了解什么呢？
玩家在此刻想要了解什么呢？
你希望玩家在此刻感受到什么呢？如何给予反馈能产生这种感受？
玩家在此刻想要感受到什么呢？她们有机会去建立一种情景来得到她们想要的感受吗？
玩家此刻的目标是什么？什么样的反馈有助于她们更接近这个目标呢？

* 透镜58 多汁的透镜
有干巴巴的界面，也有多汁的界面。为设计出多汁的界面：
界面，给了玩家行为持续的反馈吗？
玩家的行为，产生了二级动作吗？二级动作是否强大和有趣呢？
多汁系统在奖励玩家的时候，会同时用多种方法哦！我在奖励玩家的时候，我能用多少种方法呢？我能找到更多方法吗？

业界良心：
这个多汁的界面，其实做的经典的是“Candy Crush”,效果相当好。
1. 地图上，玩家所在最新位置，有光晕在动。
2. 糖果画得绚丽饱满，想舔。
3. 玩家的一个行动，可能引发二级动作（糖果爆炸等），强大而有趣。
4. 按钮一动一动的。


* 透镜59 渠道和维度的透镜
任何界面的重要目标是传达信息。确定出传达必要的信息的最佳方式。步骤：
1. 列出所有信息并且划分优先等级。
   不是所有的信息都重要，因此要对信息划分等级： 每时每刻都要看的信息、经常看的信息、只需偶然看看的信息。
2. 列出信息传达的渠道
   也就是显示信息的区域，比如屏幕顶部、右下角，音效、音乐，角色聊天泡泡等。
3. 把信息映射到渠道上
   把各类信息映射到不同的渠道上。重要的信息，在最重要的渠道上。方法：部分靠直觉，部分靠经验，大部分靠反复试验---绘制很多草图。
4. 信息的维度玩家从游戏中得到的反馈包括方方面面的内容：例如评判，奖励，指引，鼓励和挑战。
利用这个透镜来确保你的反馈循环能产生你想要的体验。
在游戏的每个时刻，都问问自己以下的问题：

   每一个信息渠道都有多种维度：
    显示出数字
    数字的颜色
    数字的大小
    数字的字体
   当你在一个渠道上用多种维度来强化一项信息时，能够让你想要传达的信息变得非常清晰（多汁）。
对渠道和维度的出色利用能够打造出一个简练和布局良好的界面。

** 透镜描述
选择如何去把游戏信息映射到各种渠道和维度上是设计游戏界面的核心。问：
有哪些数据需要传达给玩家呢？又有哪些数据需要从玩家那里传来呢？
哪些数据是最重要的？
我有哪些渠道能够用来传达这些数据？
哪些渠道最合适传达哪些数据？为什么？
在不同渠道上，有哪些维度是可用的？
我该如何利用这些维度呢？

** 扩展描述


** 应用



* 透镜61 兴趣曲线的透镜
兴趣曲线是你作为游戏设计师能用上的最有用和最具多用途的工具。为了了解玩家的兴趣在你设计的体验过程
中随时间是如何变化的，问：

假如我对我的体验绘制一条兴趣曲线，那它大概是什么样的形状的？
它有一处勾人的地方吗？
它有着兴趣的逐步提升，且具备周期性的休息中断吗？
体验里，有一个比任何事情都有趣的大结局吗？
什么样的调整，能让我拥有一条更棒的兴趣曲线吗？
在兴趣曲线中有分形结构吗？它应该具备吗？
我直觉觉察到的兴趣曲线，和观察玩家所了解到的兴趣曲线一致程度如何？
如果让玩家来绘制兴趣曲线，是怎么样的呢？


* 透镜  66  障碍的透镜  <----->透镜25  目标的透镜
好莱坞电影剧本创作的古老箴言：
一个好的故事主要组成材料是：1）一个有着特定目标的角色 2）阻碍他达成目标的各种障碍。
一个有着各种障碍的目标是值得追求的。这个透镜，与“目标透镜”属于矛盾透镜，相互相成。利用它来确保你的各种障碍是玩家想要克服的障碍。
1. 主角和目标有着什么样的关系？为什么角色会在意这个目标？
2. 角色和目标之间有着哪些障碍？
3. 在这些障碍背后存在敌对的双方吗？主角和敌对双方之间的关系是什么样的？
4. 这些障碍在难度上是逐渐提升的吗？
5. 有人说，障碍越大，故事越好，你的障碍足够大吗？它们还可以足够大吗？
6. 出色的故事往往包含着主角为了克服障碍所作出的转变。你的主角是如何转变的？

* 透镜#72  间接控制的透镜

使用间接的（而有效）手段，让玩家被微妙地影响来获得设计者设定的最佳体验。

** 间接控制手段一：限制选择
通过提供有限的选择，把玩家诱导到有限的某选择上。这么搞，给玩家一种自由感，其实比给玩家填空题（最大自由）进行了限制。
而且选择自身的设定上就可达到进行控制的意图。
相比最大自由，人们其实喜欢和认可这种限制。
例子就是作者在公园卖不同口味糖果：
1.让顾客自己报需要什么，顾客迟疑并不知道该如何报。
2.报给顾客60种口味，顾客晕菜并且恐惧。
3.让顾客从6种所谓最受欢迎的口味中选择，顾客就高兴了。
 
** 间接控制手段二：目标
通过设置目标来控制玩家，是最简单最常用的手段。
一旦设置了清晰且可以达成的目标后，你就可以通过目标来雕琢你的游戏世界了。
玩家只会去那些有目标的场所。
玩家只会做满足目标的事情。

** 间接控制手段三：界面
（原文中文译文没看懂，需要看英文原文）
大明的考试结束界面中，如果玩家20题中有错题，则界面中有一个很大的按钮
“我不服，要全对”和一个很小的按钮“算了，我认栽”。
前面那个大按钮是要花钱的。
通过这种界面控制，间接诱导玩家花钱。

** 间接控制手段四：视觉设计
一些视觉上的设计，能微妙、润物无声地控制（诱导）玩家的行为。作者给出的
例子：玩家面对宫殿王座的行为：直接飞过去，闪到两边去，都由美术设计（画线）
诱导成功了。
项目Z的地图上，姐姐头像面对最新关卡一闪一闪，也是类似。

** 间接控制手段五：角色
角色也是间接控制玩家的手段。
如果能让玩家在意角色----让他们真心去服从、保护、帮助和毁灭这些角色，你就
有了很好的工具来帮助你控制玩家愿意尝试去做的事。

** 间接控制手段六：音乐
用音乐来控制游戏节奏。
快餐店和商场一直在用这种手段。



** 提问

想让玩家做什么事情？
是否通过“设定限制”来让玩家做这些事情吗？
是否通过“设定各种目标”来让玩家做这些事情吗？
是否通过“设定界面”来让玩家做这些事情吗？
是否通过“用视觉设计”来让玩家做这些事情吗？
是否通过“角色”来让玩家做这些事情吗？
是否通过“音乐（音效）”来让玩家做这些事情吗？

还有什么方法，我能用来控制玩家，但又没有侵害玩家的自由感？skiner-box？

* 透镜#73  合谋的透镜

角色应该完全满足他们在游戏中扮演的角色，但只要可能，他们也要成为服从游戏设计师的仆役，为设计师的目标而
努力，建立玩家的体验。
为确保你的角色是为这种责任而生的，问：
我希望玩家体验到什么？
如何让角色能满足这些体验，且不损害他们在游戏中目标？

* 透镜#82 内在矛盾的透镜

内在矛盾是糟糕设计的本质。
Free from inner contradictions-----消灭内在矛盾

我的游戏的目的是什么？
   给玩家轻松、幽默、懒惰的娱乐。
我游戏中的每个子系统的目的是什么？
   需要列表。
在我游戏中，有什么东西是从根本上抵触这些目的的呢？
倘若这样，如何才能改变这种情况呢？

  
* 透镜101：正能量的透镜
相同一个内容，可以用不同的方式来表达，可以让玩家有完全不同的感受。
尽量用充满正力量的、乐观的、积极的、鼓励的、向上的方式与玩家交流沟通或展示。

（例如：1、手机游戏界面上的关闭按钮有两种表达方式，一个是右上角放一个“×”，一个是右下角放一个“√”。

2、将冷冰冰的“提示”改用语气词(哇哦！)或称赞词（恭喜你/你真棒！））

问一下你自己：

你的设计是不是可以用另外一种方式来表达，更能够让人接受呢？

你的设计是不是可以用另外一种方式来表达，更能够让玩家充满爱，感恩和power呢！
* 透镜102：得到失去的透镜
让玩家有得到的感觉，尽量减少失去的感觉。
原理：
同样数量N的<奖励|物品|...>，
1. 玩家喜欢的是由少到多的变化过程，以至于到N
 原因：喜欢得到。
 
2. 玩家不喜欢的是由多到少的变化过程，以至于到N
 原因：讨厌失去。

案例：
巴fang说的那个卖糖的售货员。他的顾客最多，就是他称一斤糖，少放到秤里面，然后一点一点加上去，顾客喜欢。但有的
售货员抓一大把到秤里面，然后一点一点减少，直到一斤。然后顾客就不高兴了。


* 透镜103：魔法尺寸的透镜

来源：
项目Z的安卓版本体验不错了。
刚移植到iOS的时候，感觉特别恶心，主要是各种元素的尺寸不对。尽管游戏逻辑、
美术等，都与安卓一样，体验为什么差异那么大呢？

于是经过思考，发现了魔法尺寸的透镜。

对于特定设备A和它的分辨率P， 存在且仅存在最优的游戏界面尺寸S1、
人物尺寸S2、物品尺寸S3和字体尺寸S4。
我们称它为最优尺寸，或魔法尺寸。
在魔法尺寸下，玩家感觉界面最清晰、最舒服。
如果游戏界面、物件实际尺寸小于最优尺寸，则感觉很难受，不仅看不清楚，
而且显得游戏小气、物件密集等。
问自己问题：
** 我们游戏的各种尺寸，是魔法尺寸吗？
** 如果不是，应该如何达到呢？


* 透镜104： 凯尔文勋爵的透镜

一切都要量化才行。数据依据是最准确、最客观的度量标准，为游戏设计和改进提供了刚性论据。
所以需要在游戏设计、参考、改进过程中，大量使用统计学手段。

** 实例：


*** 以开始界面的设置按钮为例：

项目Z 的设置按钮 (75,72)
找你妹1的开始界面按钮(92,93)
农场英雄 的设置按钮 (120,117)
dump die  (79,85)
小小盗贼的设置按钮(91,96)

结论：
项目Z设置按钮太小，不仅感受到了，而且数据支持了。

最终：
改。

** 项目Z物件大小
项目Z物件在大小上，分布比找你妹1扩散，所以看起来怪怪的，证据如下。
使用R软件，分别统计101个项目Z和找你妹1物件，
z1_chang: 1的物件长度
z2_chang: 项目Z的物件长度
z1_gao: 1的物件高度
z2_gao: 项目Z的物件高度
mianji1： 1物件的面积
mianji2： 项目Z物件的面积
mean:均值
min:最小数
max:最大数
sd:标准均方差

> mean(z1_chang)
143.1287

> mean(z1_gao)
132.9802


> mean(z2_chang)
129.3762


> mean(z2_gao)
134.5347


> summary(z1_gao)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
     40      96     120     133     162     258 
> summary(z2_gao)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   39.0    95.0   131.0   134.5   162.0   293.0 



> summary(z1_chang)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   32.0   109.0   146.0   143.1   169.0   380.0 



> summary(z2_chang)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   31.0    90.0   126.0   129.4   166.0   447.0 


> summary(mianji1)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   2772   11780   17430   19850   25260   75080 
> summary(mianji2)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1829    9177   16490   18910   23710  110400 

> sd(mianji1)
 12214.73
> sd(mianji2)
 15338.41

结论

一、 项目Z的物件，大小上很不平衡，以物件面积为度量标准，表现：
A  项目Z最大的面积为110400，远远超过找你妹1的最大物件75080
B. 项目Z最小的面积为1829(一个小音符)，远小于找你妹1的最小物件2772
C. 项目Z物件的标准方差为15338.41，比找你妹1物件标准方差12214.73大。

建议：
把项目Z过于大的物件改小些，过于小的物件改大些。这样总体上分布平衡。

二、项目Z物件的长和高，最小数值与找你妹1的类似。

三、项目Z物件的高度，最大数值远远大于找你妹1物件高度的最大数值：
> summary(z1_gao)
      Max. =  258 
> summary(z2_gao)
    Max. =   293.0 

四、项目Z物件的长度，最大数值远远大于找你妹1物件长度的最大数值：
> summary(z1_chang)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   32.0   109.0   146.0   143.1   169.0   380.0 



> summary(z2_chang)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   31.0    90.0   126.0   129.4   166.0   447.0 

   建议：把项目Z特别高或特别长的物件去掉，或改得不那么高或那么长。
   
五、 项目Z物件平均面积比找你妹1的小
summary(mianji1)   Mean=19850
summary(mianji2)   Mean=18910
但有趣的是：

六： 每屏物件，找你妹1有26个，项目Z才23个。统计数据：
找你妹1平均值	25.86	 项目Z平均值	22.98

由五和六得出结论：
我们物品摆放算法导致更多空隙，所以每屏物品摆放效率比找你妹1低。


最终：
改了物件大小，200左右物件调整大了，初步效果是：看起来更美观，且更加类似找你妹1。
